version: '3'
services:
  trainhis:
    image: hisrepeat:latest
    volumes:
      - ~/implements/HisRepItself/:/workspace/HisRepItself/
      - ~/dataset/.:/workspace/HisRepItself/datasets/
    working_dir: /workspace/HisRepItself/
    command: python3 stagcn_cmu_3d.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
